export const allLandingPages = [
  { name: "Marketing", path: "/marketing" },
  { name: "Business", path: "/business" },
  { name: "Invitation", path: "/invitation" },
  { name: "Quotes", path: "/quotes" },
  { name: "Resume", path: "/resume" },
  { name: "Flyer", path: "/flyer" },
  { name: "Calendar", path: "/calendar" },
  { name: "Bridal Shower", path: "/bridal-shower" },
  { name: "Logo", path: "/logos" },
  { name: "Wedding", path: "/wedding" },
  { name: "Birthday", path: "/birthday-invitation" },
  { name: "Baby Shower", path: "/baby-shower-invitation" },
  { name: "Party", path: "/party-invitation" },
  { name: "Brochure", path: "/brochure-design" },
  { name: "Poster", path: "/poster" },
  { name: "Indian", path: "/indian" },
  { name: "Baptism", path: "/baptism" },
  { name: "Gujarati", path: "/gujarati" },
  { name: "English", path: "/english" },
  { name: "Hindu", path: "/hindu" },
  { name: "Muslim", path: "/muslim" },
  { name: "Punjabi", path: "/punjabi" },
  { name: "Christian", path: "/christian" },
  { name: "Tamil", path: "/tamil" },
  { name: "Pregnancy Announcement", path: "/pregnancy-announcement" },
  { name: "Birth Announcement", path: "/birth-announcement" },
  { name: "Christening", path: "/christening" },
  { name: "Engagement", path: "/engagement" },
  { name: "Engagement Party", path: "/engagement-party" },
  { name: "Party Invitation", path: "/party-invitation" },
  { name: "Haldi Ceremony", path: "/haldi-ceremony" },
  { name: "Rehearsal Dinner", path: "/rehearsal-dinner" },
  { name: "Save The Date", path: "/save-the-date" },
  { name: "South Indian", path: "/south-indian" },
  { name: "Biodata", path: "/biodata" },
  { name: "Cards", path: "/cards" },
  { name: "Review", path: "/review" },
];
